name: build_docker

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          echo 本次构建的版本为：${{ github.ref_name }}
          env

  build_web:
    needs: [checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
      
  build_service:
    needs: [checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Install
        run: cd service | 
            npm ci

      - name: Build
        run: cd service |
             npm run build

  build_docker:
    needs: [build_web, build_service]
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-plus:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-plus:latest
